### ISSUE TITLE
No support for windows?

### ISSUE THREAD

**Issue by EvgeniiDev** [bashkirtsevich-llc/aiobtdht#4]
trying to run example on win10 (Python 3.10), but get this:
(<class 'ImportError'>, ImportError("cannot import name 'getrandom' from 'os' ...\\Python310\\lib\\os.py)"), <...>) 
error in file utils.py

**Comment by mm-lang** [comment]
I use python version 3.9
By consulting the official Python documentation, os.getrandom seems to only run on Linux systems.
Python doc: https://docs.python.org/3.9/library/os.html

**Comment by Gesugao-san** [comment]
Windows 10 22H2, Python 3.11.5.

Sadly, same problem.

```py
Traceback (most recent call last):
  File "C:\censored\example.py", line 7, in <module>
    from aiobtdht import DHT
  File "C:\Python311\Lib\site-packages\aiobtdht\__init__.py", line 1, in <module>
    from aiobtdht.dht import DHT
  File "C:\Python311\Lib\site-packages\aiobtdht\dht.py", line 10, in <module>
    from .schemas import ANNOUNCE_PEER_ARGS
  File "C:\Python311\Lib\site-packages\aiobtdht\schemas.py", line 1, in <module>
    from .utils import decode_id
  File "C:\Python311\Lib\site-packages\aiobtdht\utils.py", line 3, in <module>
    from os import getrandom
ImportError: cannot import name 'getrandom' from 'os' (C:\Python311\Lib\os.py)
```

**Comment by bashkirtsevich** [comment]
OK, I will fix it.

**Comment by Gesugao-san** [comment]
> OK, I will fix it.

Oh, thank you very much! I thought this repository was already dead.

**Comment by bashkirtsevich** [comment]
> ```python
> cannot import name 'getrandom' from 'os'
> ```
Fixed
https://github.com/bashkirtsevich-llc/aiobtdht/commit/f99d881e9b992da13519721e251912c32a566cd7
